###
### This workflows will create a realease when the casarundata main branch
### is tagged with 'v*' and pushed up
###

name: Actions for each push or pull

on:
  create:                            # Workflow runs on push or pull request events but only for the main branch

jobs:

  deploy:

    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    runs-on: ubuntu-latest           # The type of runner that the job will run on

    permissions:
      contents: write

    steps:                           # Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v2    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: create release
        uses: ncipollo/release-action@v1   # https://github.com/ncipollo/release-action
        #with:
        #  token: ${{ secrets.YOUR_GITHUB_TOKEN }}
